services:
  nginx_rtmp:
    container_name: nginx_rtmp
    build: ./nginx_rtmp
    ports:
      - 1935
      - 80:80
    tty: true
    volumes:
      - ./data:/usr/share/nginx/html
      - ./log/nginx_rtmp/:/var/log/nginx/
    restart: always

  php_fpm:
    container_name: php_fpm
    build: ./php_fpm
    restart: always
    volumes:
      - ./data:/usr/share/nginx/html

  cleanup:
    container_name: cleanup
    build: ./cleanup
    environment:
      # Max size for the recording directory in MB
      MAX_SIZE_MB: 256 # 1GB
    volumes:
      # Mount the recording directory to be monitored
      - ./data/hls:/hls
    restart: always
